// import Header from "@/components/header";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrate = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tara Calculator",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${montserrate.className} p-0 m-0 box-border`}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          <div className="text-white">{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
